import type { Speaker } from "./types/speakers";

export const speakers: Speaker[] = [
  {
    image: "/images/speakers/slyvestor-george.webp",
    name: "Sylvestor George",
    title: "Staff Software Engineer at Slack",
    twitter: "tbd",
    mastodon: "tbd",
    linkedin: "tbd",
    github: "tbd",
  },
  {
    image: "/images/speakers/slyvestor-george.webp",
    name: "Erika Blue",
    title: "Head of engineering at Spotify",
    twitter: "tbd",
    mastodon: "tbd",
    linkedin: "tbd",
    github: "tbd",
  },
  {
    image: "/images/speakers/slyvestor-george.webp",
    name: "Erika Blue",
    title: "Head of engineering at Spotify",
    twitter: "tbd",
    mastodon: "tbd",
    linkedin: "tbd",
    github: "tbd",
  },
  {
    image: "/images/speakers/slyvestor-george.webp",
    name: "Erika Blue",
    title: "Head of engineering at Spotify",
    twitter: "tbd",
    mastodon: "tbd",
    linkedin: "tbd",
    github: "tbd",
  },
  {
    image: "/images/speakers/slyvestor-george.webp",
    name: "Erika Blue",
    title: "Head of engineering at Spotify",
    twitter: "tbd",
    mastodon: "tbd",
    linkedin: "tbd",
    github: "tbd",
  },
  {
    image: "/images/speakers/slyvestor-george.webp",
    name: "Erika Blue",
    title: "Head of engineering at Spotify",
    twitter: "tbd",
    mastodon: "tbd",
    linkedin: "tbd",
    github: "tbd",
  },
  {
    image: "/images/speakers/slyvestor-george.webp",
    name: "Erika Blue",
    title: "Head of engineering at Spotify",
    twitter: "tbd",
    mastodon: "tbd",
    linkedin: "tbd",
    github: "tbd",
  },
  {
    image: "/images/speakers/slyvestor-george.webp",
    name: "Erika Blue",
    title: "Head of engineering at Spotify",
    twitter: "tbd",
    mastodon: "tbd",
    linkedin: "tbd",
    github: "tbd",
  },
];
