import type { Speaker } from "./types/speakers";

export const speakers: Speaker[] = [
  {
    image: "/images/speakers/alex.webp",
    name: "GHOST",
    title: "Absolutely Poggers",
    twitter: "onlyspaceghost",
    mastodon: "#",
    linkedin: "#",
    github: "#",
  },
  {
    image: "/images/speakers/alex.webp",
    name: "GHOST",
    title: "Absolutely Poggers",
    twitter: "onlyspaceghost",
    mastodon: "#",
    linkedin: "#",
    github: "#",
  },
  {
    image: "/images/speakers/alex.webp",
    name: "GHOST",
    title: "Absolutely Poggers",
    twitter: "onlyspaceghost",
    mastodon: "#",
    linkedin: "#",
    github: "#",
  },
  {
    image: "/images/speakers/alex.webp",
    name: "GHOST",
    title: "Absolutely Poggers",
    twitter: "onlyspaceghost",
    mastodon: "#",
    linkedin: "#",
    github: "#",
  },
  {
    image: "/images/speakers/alex.webp",
    name: "GHOST",
    title: "Absolutely Poggers",
    twitter: "onlyspaceghost",
    mastodon: "#",
    linkedin: "#",
    github: "#",
  },
  {
    image: "/images/speakers/alex.webp",
    name: "GHOST",
    title: "Absolutely Poggers",
    twitter: "onlyspaceghost",
    mastodon: "#",
    linkedin: "#",
    github: "#",
  },
  {
    image: "/images/speakers/alex.webp",
    name: "GHOST",
    title: "Absolutely Poggers",
    twitter: "onlyspaceghost",
    mastodon: "#",
    linkedin: "#",
    github: "#",
  },
  {
    image: "/images/speakers/alex.webp",
    name: "GHOST",
    title: "Absolutely Poggers",
    twitter: "onlyspaceghost",
    mastodon: "#",
    linkedin: "#",
    github: "#",
  },
];
